# Pull request validation for Linux against the `dev` and `master` branches
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference
trigger:
  branches:
    include:
      - dev
      - master
  paths:
    exclude:
      - '*.md'
      - 'docs/*'

pr:
  autoCancel: true
  branches:
    include:
      - dev
      - master

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

jobs:
  - template: azure-pipeline.template.yaml
    parameters:
      name: 'Linux'
      vmImage: 'ubuntu-latest'
      runIntegrationTests: true
