# Release task for PbLib projects
# See https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema for reference

pool:
  vmImage: windows-latest
  demands: Cmd

trigger:
  branches:
    include:
      - refs/tags/*

variables:
  - group: signingSecrets #create this group with SECRET variables `signingUsername` and `signingPassword`
  - group: nugetKeys #create this group with SECRET variables `nugetKey`
  - name: githubConnectionName
    value: PbReleaseNotes
  - name: projectName
    value: Incrementalist
  - name: githubRepositoryName
    value: petabridge/Incrementalist

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK from global.json'
  inputs:
    useGlobalJson: true

- task: UseDotNet@2
  displayName: 'Use .NET SDK 8.0'
  inputs:
    packageType: sdk
    version: 8.0.416
  
# Version bump from release notes
- task: PowerShell@2
  displayName: 'Update version from RELEASE_NOTES.md'
  inputs:
    targetType: 'inline'
    script: './build.ps1'

# Create NuGet packages
- task: PowerShell@2
  displayName: 'Create NuGet packages'
  inputs:
    targetType: 'inline'
    script: 'dotnet pack -c Release -o bin\nuget'

# Push to NuGet
- task: PowerShell@2
  displayName: 'Push NuGet packages'
  inputs:
    targetType: 'inline'
    script: |
      $packages = Get-ChildItem -Path "bin\nuget\*.nupkg"
      foreach ($package in $packages) {
          dotnet nuget push $package --api-key "$(incrementalistKey)" --source "https://www.nuget.org/api/v2/package"
      }

# Create GitHub Release
- task: GitHubRelease@0
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: $(githubConnectionName)
    repositoryName: $(githubRepositoryName)
    title: '$(projectName) v$(Build.SourceBranchName)'
    releaseNotesFile: 'RELEASE_NOTES.md'
    assets: |
     bin\nuget\*.nupkg
